language: node_js

node_js:
- '13'

install:
- npm install

script:
- npm run test
- npm run build

deploy:
  provider: firebase
  token:
    secure: QVSl/7S/IbyoUKD0cLDQEO/YH3R1DdIy31ldqc7fHnZ8bfQegByN1yFmaRbzu8L1CjNPggMARj8YlFxH8nMB2qojpWvc/7F/dMfrLnD009idgN/LJpUhhTADr9KBpc6mnd3DxMYpitGjoa1R61DSY/zcRM44DsD6SatKb1klCD/Ik1OPUGJaV21ahlUVXPNAc7TwDDsF3d/mjOIbW8Wy8y+gCKt0uU8iYidisI1sYnzcJ60CZ2qL+AZu99uCn3+Losb0RnxPPdaeZCPBBG8lHKwf0TKvxD3nhS4Ui37WtSSLdORH3FvMpM1JVjOMl22nWkQt2U3ZRAo4zOp1u9a5pJ21nZxKbphxM2uKNF05MolKWSzKGd2Qv+R62ycyAUyUQg60eXLMVBjbYo7K6dHnZFjne1Arewp0Ef0RYEqiOruQRLi/SqOuzAY8fDI2bfXzZHAyfvChhjdDsJPLOek3hGIqGHvIqp+oFnZfipaATGCUlgryod9QO/JK3Bg95biZ17P5aHd5covgzk89fpQF8qCySQShVkfK+ld/hDJHAnSfoURiVYMpKBOQ3cjf3YAVgjHAZqW8jFPyYaPd4s2JQJx2DQ+XisFvZ9jceJ5dFXEa+opGcZHlzDJE5EA1jW2u6hgMfYmG6gPAKY3BlpkblwXWucFW2aYZVhcIMFRs8Fc=
  skip_cleanup: true
  on:
    branch: master